defaults:
  - _self_
  - /modules@healvaetrainparams.criterion: mse
  - /modules@healvaetrainparams.optimiser: adam

healvae:
  _target_: healdit.schemas.HEALVAEConfig
  depths: [2, 2]
  edge_feat_dim: 4
  edge_embed_dim: 16
  input_feat_dim: 2
  lat_lon_res: [181, 360]
  node_feat_dim: 16
  node_hidden_dim: 16
  n_edge_closest: 4 
  output_feat_dim: 2
  starting_n: 4
  z_dim: 16
  
healvaetrainparams:
  _target_: healdit.schemas.TrainParams
  accumulation_steps: 32
  batch_size: 1
  data_path: "/home/benjamin/healdit/data/era5_data_6h_1degree_2011_2016_rechunked.zarr"
  device: "cpu"
  epochs: 1
  gradient_threshold: 0.0
  max_norm: 1.0
  train_start: "2011-01-01T00:00:00"
  train_end: "2015-12-31T18:00:00"
  val_start: "2016-01-01T00:00:00"
  val_end: "2016-12-31T18:00:00"

